setup_arguments:
    imagenet_path:
      help: "folder containing imagenet1k data organized as follows: https://www.kaggle.com/c/imagenet-object-localization-challenge/overview/description"
      value: 'imagenet_data'
    num_workers: 4
    num_epochs: 2

arguments:
  expansion_factor: 64
  context_size: 197
  d_in: 1024
  model_name: "wkcn/TinyCLIP-ViT-8M-16-Text-3M-YFCC15M"
  hook_name: "blocks.9.mlp.hook_pre"
  hook_layer: 9
  dead_feature_window: 5000
  use_ghost_grads: True
  feature_sampling_window: 1000
  from_pretrained_path: null


  b_dec_init_method: "geometric_median"

  lr: 0.0004
  l1_coefficient: 0.00008
  lr_scheduler_name: "constant"
  train_batch_size_tokens: 4096
  lr_warm_up_steps: 5000

  n_batches_in_buffer: 32
  store_batch_size: 32
  normalize_activations: "none"  # not implemented for vision

  log_to_wandb: True
  wandb_project: "vit_sae_training"
  wandb_entity: null
  wandb_log_frequency: 100
  eval_every_n_wandb_logs: 10
  run_name: nulls

  device: "cuda"
  seed: 42
  n_checkpoints: 10
  checkpoint_path: null
